In [49]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [50]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [51]:
# we want to calculate projected salaries for next year based upon inflation
# rate of 3%.

df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary(salary):
    return salary *1.03

df_salary['salary_year_avg'].apply(projected_salary)

28        112785.00
77        144200.00
92        123600.00
100       235068.66
109        91670.00
            ...
785624    143392.48
785641    154500.00
785648    228531.25
785682    162225.00
785692    162225.00
Name: salary_year_avg, Length: 22003, dtype: float64

In [52]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

In [53]:
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [54]:
# lets try writing this again with an anonymous function 

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

In [55]:
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [20]:
# in the dataframe, job skills are displayed as a string. we want to SystemErrorit as a list

df['job_skills'][1]

"['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']"

In [56]:
type(df['job_skills'][1])

str

In [57]:
# AST (abstaract syntax tree) is a Python library that allows you to parse 
# and analyze Python code as a tree structure.
# It can be used to convert a string representation of a list into an 
# actual list object.

import ast

ast.literal_eval(df['job_skills'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [58]:
type(ast.literal_eval(df['job_skills'][1]))

list

In [ ]:
def clean_list(skill_list):
    return ast.literal_eval(skill_list)

df['job_skills'] = df['job_skills'].apply(clean_list)

In [ ]:
# this error is due to nan values in thecolumn.

def clean_list(skill_list):
    if pd.isna(skill_list):
        return []
    else:
        return ast.literal_eval(skill_list)
    
df['job_skills'] = df['job_skills'].apply(clean_list)

In [60]:
df['job_skills'][0]
df['job_skills'][1]

"['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']"

In [61]:
type(df['job_skills'][0])

float

In [62]:
df['job_skills'] = df['job_skills'].apply(lambda skill_list:ast.literal_eval(skill_list)if pd.notna(skill_list) else skill_list  )

In [63]:
type(df['job_skills'][1])

list

In [65]:
df['job_skills'][1]

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

## Calculate projected salary next year

- Senior roles assume 5%
- Other roles assume 3%

In [70]:
def projected_salary(row):
    if "senior" in row['job_title_short']:
        return row['salary_year_average'] * 1.05
    else:
        return row['salary_year_avg'] * 1.03

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis =1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']].sample(10)

              job_title_short  salary_year_avg  salary_year_inflated
79140           Data Engineer         135000.0              139050.0
212986    Senior Data Analyst         100000.0              103000.0
202371           Data Analyst         153000.0              157590.0
27320           Data Engineer         140000.0              144200.0
320250           Data Analyst         130000.0              133900.0
228288           Data Analyst          90000.0               92700.0
510161  Senior Data Scientist         205000.0              211150.0
133365         Data Scientist          60000.0               61800.0
257279         Data Scientist         150000.0              154500.0
40271           Data Engineer         115000.0              118450.0